DROP TYPE DIRECCION;
DROP TYPE PERSONA;
DROP TYPE ALUMNO;

----
SET SERVEROUTPUT ON;

------
/*4.1*/
------
CREATE OR REPLACE TYPE DIRECCION AS OBJECT
(
	CALLE VARCHAR2(25),
	CIUDAD VARCHAR2(20),
	CODIGO_POSTAL NUMBER(5));
/
	
CREATE OR REPLACE TYPE PERSONA AS OBJECT
(
	CODIGO NUMBER,
	CIUDAD VARCHAR2(35),
	DIREC DIRECCION,
	FECHA_NAT DATE);
/
CREATE OR REPLACE TYPE ALUMNO AS OBJECT
(
	PERS PERSONA,
	NOTAE1 NUMBER,
	NOTAE2 NUMBER,
	NOTAE3 NUMBER
	);
/

DECLARE
	D DIRECCION:=DIRECCION('Calle la paz','Mostoles',28936);
	P PERSONA:=PERSONA(1,'Madrid',D,SYSDATE);
	T_ALUMNO ALUMNO;
BEGIN
	T_ALUMNO:=NEW ALUMNO(P,10,7,5);
	
	DBMS_OUTPUT.PUT_LINE('SE HA CREADO EL ALUMNO '||T_ALUMNO.PERS.CODIGO);
END;
/

------
/*4.2*/
------
CREATE OR REPLACE TYPE ALUMNO AS OBJECT
(
	PERS PERSONA,
	NOTAE1 NUMBER,
	NOTAE2 NUMBER,
	NOTAE3 NUMBER,
	MEMBER FUNCTION GET_MEDIA RETURN NUMBER
	);
CREATE TYPE BODY ALUMNO AS
	MEMBER FUNCTION GET_MEDIA RETURN NUMBER IS
	BEGIN
	
	RETURN (NOTAE1+NOTAE2+NOTAE3)/3;
	END GET_MEDIA;
END;
/

------
/*4.3*/
------
CREATE TABLE ALUMNOS2 OF ALUMNO;

DECLARE
	D DIRECCION:=DIRECCION('Calle la paz','Mostoles',28936);

	P1 PERSONA;
	P2 PERSONA;
	P3 PERSONA;
	
	A1 ALUMNO;
	A2 ALUMNO;
	A3 ALUMNO;
	
BEGIN
	P1:=PERSONA(1,'Madrid',D,SYSDATE);
	P2:=PERSONA(2,'Barcelona',D,SYSDATE);
	P3:=PERSONA(3,'Bilbo',D,SYSDATE);
	
	A1:=NEW ALUMNO(P1,5,6,5);
	A2:=NEW ALUMNO(P2,7,4,5);
	A3:=NEW ALUMNO(P3,7,10,5);
	
	INSERT INTO ALUMNOS2 VALUES(A1);
	INSERT INTO ALUMNOS2 VALUES(A2);
	INSERT INTO ALUMNOS2 VALUES(A3);

END;
/

------
/*4.4*/
------
CREATE OR REPLACE TYPE TELEFONO AS VARRAY(3) OF VARCHAR2(9);
CREATE TABLE AGENDA(
	NOMBRE VARCHAR2(15),
	TELEF TELEFONO);

INSERT INTO AGENDA VALUES('MANUEL',TELEFONO('669699696','3452334','664234'));
INSERT INTO AGENDA(NOMBRE, TELEF) VALUES
	('MARTA', TELEFONO('693442344'));
	
CREATE OR REPLACE FUNCTION GETPRIMERTLFDENOMBRE(N VARCHAR2) RETURN NUMBER
IS
	TEL TELEFONO:=TELEFONO(NULL,NULL,NULL);
	PRIMERTELEFONO NUMBER;
BEGIN
	SELECT TELEF INTO TEL FROM AGENDA WHERE NOMBRE=N;
	PRIMERTELEFONO:=TEL(1);
	RETURN PRIMERTELEFONO;
END GETPRIMERTLFDENOMBRE;
/
------
/*4.5*/
------
CREATE TYPE PERSONAS AS VARRAY(5) OF PERSONA;
CREATE TABLE GRUPOS(
	NOMBRE VARCHAR2(15),
	INTEGRANTES PERSONAS);
DECLARE
	DIR DIRECCION:= DIRECCION('AAA','BBB',123);
	P1 PERSONA:= PERSONA(6,'VALENCIA',DIR,SYSDATE);
	P2 PERSONA:= PERSONA(7,'CACA',DIR,SYSDATE);
	P3 PERSONA:= PERSONA(8,'SSS',DIR,SYSDATE);
	P4 PERSONA:= PERSONA(9,'PAPA',DIR,SYSDATE);
	P5 PERSONA:= PERSONA(10,'PEPE',DIR,SYSDATE);
	P6 PERSONA:= PERSONA(11,'PIPI',DIR,SYSDATE);
	
	G1 PERSONAS:=PERSONAS(P1,P2);
	G2 PERSONAS:=PERSONAS(P3);
	G3 PERSONAS:=PERSONAS(P4,P5,P6);
BEGIN
	INSERT INTO GRUPOS VALUES('GRUPO1',G1);
	INSERT INTO GRUPOS VALUES('GRUPO2',G2);
	INSERT INTO GRUPOS VALUES('GRUPO3',G3);

	
END;
/

DECLARE
	CURSOR C1 IS SELECT * FROM GRUPOS;
BEGIN
	FOR I IN C1 LOOP
		DBMS_OUTPUT.PUT_LINE('MOSTRANDO DATOS DE '||I.NOMBRE);
		FOR J IN 1..I.INTEGRANTES.COUNT LOOP
			DBMS_OUTPUT.PUT_LINE(I.INTEGRANTES(J).CIUDAD);
		END LOOP;
	END LOOP;
END;
/
------
/*4.6*/
------
CREATE TYPE TABLA_ANIDADA AS TABLE OF DIRECCION;

CREATE TABLE EJEMPLO_TABLA_ANIDADA
(
	ID NUMBER(2),
	APELLIDOS VARCHAR2(35),
	DIREC TABLA_ANIDADA
)
NESTED TABLE DIREC STORE AS DIREC_ANIDADA;
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(1, 'RAMOS', TABLA_ANIDADA(
													DIRECCION('CALLE 1','MADRID','12313'),
													DIRECCION('CALLE 2','BARCELIONA','111'),
													DIRECCION('CALLE 3','MADRID','6666')
													)
										);
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(2, 'GOMEZ', TABLA_ANIDADA(
													DIRECCION('CALLE 4','BILBO','12313'),
													DIRECCION('CALLE 5','SAN SEBASTIAN','111'),
													DIRECCION('CALLE 6','LOGROÑO','6666')
													)
										);
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(3, 'MUÑOZ', TABLA_ANIDADA(
													DIRECCION('CALLE 7','LA RIOJA','12313'),
													DIRECCION('CALLE 8','SANTANDER','111')
													)
										);
										
DECLARE
	NUMERODIRECCIONES NUMBER;
BEGIN
	SELECT COUNT(*) INTO NUMERODIRECCIONES FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) TT WHERE ID=1;
	DBMS_OUTPUT.PUT_LINE('EL IDENTIFICADOR 1 TIENE '||NUMERODIRECCIONES||' DIRECCIONES');
END;
/
---SUBCONSUKLTA QUE DEVUELVE QUIEN TIENE MAS DIRECCIONES ASOCIADAS---
SELECT ID, APELLIDOS FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) DIRECCION
GROUP BY ID, APELLIDOS
HAVING COUNT(*) IN (SELECT MAX(COUNT(*)) FROM EJEMPLO_TABLA_ANIDADA, TABLE(DIREC) DIRECCION
	GROUP BY ID, APELLIDOS);

DECLARE
	APELLIDOACTUAL VARCHAR2(100);
	CURSOR C1 IS 
		SELECT APELLIDOS, DIRECCION.CALLE AS NOMCALLE 
		FROM EJEMPLO_TABLA_ANIDADA, TABLE (DIREC) DIRECCION;
BEGIN
	FOR I IN C1 LOOP
		IF APELLIDOACTUAL IS NULL OR APELLIDOACTUAL!=I.APELLIDOS THEN
		DBMS_OUTPUT.PUT_LINE('MOSTRANDO LAS CALLES DE '||I.APELLIDOS||':');
		APELLIDOACTUAL:=I.APELLIDOS;
		END IF;
		DBMS_OUTPUT.PUT_LINE(I.NOMCALLE);
	END LOOP;
END;
/

------
/*4.7*/
------

CREATE OR REPLACE PROCEDURE INSERTARDIRECCIONES
	(IDENTIFICADOR VARCHAR2, DIRECCIONNUEVA DIRECCION) IS
	NUMEROITERACIONES NUMBER;
	EXISTE BOOLEAN;
BEGIN
	SELECT COUNT(ID) INTO NUMEROITERACIONES
		FROM EJEMPLO_TABLA_ANIDADA
		WHERE ID=IDENTIFICADOR;
	IF NUMEROITERACIONES=0 THEN
	DBMS_OUTPUT.PUT_LINE('NO EXISTE ESA PERSONA, NO SE PUEDE AÑADIR');
	END IF;
	IF NUMEROITERACIONES=1 THEN
		INSERT INTO TABLE
			(SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID=IDENTIFICADOR)
		VALUES(DIRECCION(DIRECCIONNUEVA.CALLE,DIRECCIONNUEVA.CIUDAD,DIRECCIONNUEVA.CODIGO_POSTAL));
		DBMS_OUTPUT.PUT_LINE('SE HA AGREGADO UNA NUEVA DIRECCION');
	END IF;
	IF NUMEROITERACIONES>1 THEN
		DBMS_OUTPUT.PUT_LINE('ERROR, HAY MAS DE UNA PERSONA ASOCIADA A ESE IDENTIFICADOR');
	END IF;
END;
/

BEGIN
	INSERTARDIRECCIONES(2,DIRECCION('CALLE 7','PARLA',34211));
END;
/

------
/*4.8*/
------

CREATE TYPE TIPO_DEP AS OBJECT(
	DEPT_NO NUMBER(2),
	DNOMBRE VARCHAR2(15),
	LOC VARCHAR2(15)
);
/
CREATE TABLE DEPARTAMENTOS OF TIPO_DEP;

CREATE TABLE EMPLEADOSDEP(
	TIPO_DEP_EMP_NO NUMBER(4),
	APELLIDO VARCHAR2(15),
	SALARIO NUMBER(6,2),
	DEPT REF TIPO_DEP
);
/
	