
CREATE OR REPLACE TYPE DIRECCION AS OBJECT
(
	CALLE VARCHAR2(25),
	CIUDAD VARCHAR2(20),
	CODIGO_POSTAL NUMBER(5));
/
	
CREATE OR REPLACE TYPE PERSONA AS OBJECT
(
	CODIGO NUMBER,
	CIUDAD VARCHAR2(35),
	DIREC DIRECCION,
	FECHA_NAT DATE);
/
CREATE OR REPLACE TYPE ALUMNO AS OBJECT
(
	PERS PERSONA,
	NOTAE1 NUMBER,
	NOTAE2 NUMBER,
	NOTAE3 NUMBER,
	MEMBER FUNCTION GET_MEDIA RETURN NUMBER
	);
/

DECLARE
	MEDIA NUMBER;
	PERSONA P:= PERSONA(1,'Madrid',
BEGIN

END;
/

CREATE OR REPLACE TYPE DIRECCION AS OBJECT(
	CALLE VARCHAR2(25),
	CIUDAD VARCHAR2(20),
	CODIGO_POST NUMBER(5),
	
	MEMBER PROCEDURE SET_CALLE(C VARCHAR2),
	MEMBER FUNCTION GET_CALLE RETURN VARCHAR2);
	/
	
//varray
CREATE OR REPLACE TYPE TELEFONO AS VARRAY(3) OF VARCHAR2(9);
CREATE TABLE AGENDA(
	NOMBRE VARCHAR2(15),
	TELEF TELEFONO);

INSERT INTO AGENDA VALUES('MANUEL',TELEFONO('669699696','3452334','664234'));
INSERT INTO AGENDA(NOMBRE, TELEF) VALUES
	('MARTA', TELEFONO('693442344'));
	
CREATE OR REPLACE PROCEDURE INSERTAR_AGENDA (N VARCHAR2, T TELEFONO) AS
BEGIN
	INSERT INTO AGENDA VALUES(N,T);
END;
/

BEGIN
	INSERTAR_AGENDA('LUIS',TELEFONO('666666666'));
	INSERTAR_AGENDA('MIGUEL',TELEFONO('6663234','23466','12356664'));
END;
/

CREATE OR REPLACE FUNCTION GETPRIMERTLFDENOMBRE(N VARCHAR2) RETURN NUMBER
IS
	TEL TELEFONO:=TELEFONO(NULL,NULL,NULL);
	PRIMERTELEFONO NUMBER;
BEGIN
	SELECT TELEF INTO TEL FROM AGENDA WHERE NOMBRE=N;
	PRIMERTELEFONO:=TEL(1);
	RETURN PRIMERTELEFONO;
END GETPRIMERTLFDENOMBRE;
/
DECLARE
	NOMBRE VARCHAR2(15):='MIGUEL';
	PRIMERTELEFONO NUMBER;
BEGIN
	PRIMERTELEFONO:=GETPRIMERTLFDENOMBRE(NOMBRE);
	DBMS_OUTPUT.PUT_LINE(PRIMERTELEFONO);
END;
/