
CREATE OR REPLACE TYPE DIRECCION AS OBJECT
(
	CALLE VARCHAR2(25),
	CIUDAD VARCHAR2(20),
	CODIGO_POSTAL NUMBER(5));
/
	
CREATE OR REPLACE TYPE PERSONA AS OBJECT
(
	CODIGO NUMBER,
	CIUDAD VARCHAR2(35),
	DIREC DIRECCION,
	FECHA_NAT DATE);
/
CREATE OR REPLACE TYPE ALUMNO AS OBJECT
(
	PERS PERSONA,
	NOTAE1 NUMBER,
	NOTAE2 NUMBER,
	NOTAE3 NUMBER);
/
