/*AÑADIR PERSONA Y DIRECCION A BBDD*/

DECLARE
	DIR DIRECCION:= DIRECCION(NULL,NULL,NULL);
	P PERSONA:= PERSONA(NULL,NULL,NULL,NULL);
	A ALUMNO;
	
BEGIN
	DIR.CALLE:='Versalles 3';
	DIR.CIUDAD:='Madrid';
	DIR.CODIGO_POSTAL:=28931;
	
	P.CODIGO:=1;
	P.CIUDAD:='Navalcarnero';
	P.DIREC:=DIR;
	P.FECHA_NAT:=SYSDATE;
	A:=NEW ALUMNO(P,0,0,0);
	
	DBMS_OUTPUT.PUT_LINE(A.PERS.CIUDAD);
END;
/

