
DECLARE
	DIR DIRECCION:= DIRECCION(NULL,NULL,NULL);
	P PERSONA:= PERSONA(NULL,NULL,NULL,NULL);
	A ALUMNO;
BEGIN
	DIR.CALLE:='Versalles 3';
	DIR.CIUDAD:='Madrid';
	DIR.CODIGO_POSTAL:=28931;
	
	P.CODIGO:=1;
	P.CIUDAD:='Navalcarnero';
	P.DIREC:=DIR;
	P.FECHA_NAT:=SYSDATE;
	A:=NEW ALUMNO(P,1,5,10);
	
	DBMS_OUTPUT.PUT_LINE(A.PERS.CIUDAD);
	DBMS_OUTPUT.PUT_LINE('NOTA 1 ' ||A.NOTAE1);
	DBMS_OUTPUT.PUT_LINE('NOTA 2 ' ||A.NOTAE2);
	DBMS_OUTPUT.PUT_LINE('NOTA 3 ' ||A.NOTAE3);
	DBMS_OUTPUT.PUT_LINE(A.GET_MEDIA);
END;
/

//Insertar alumnos en la tabla de alumnos

DECLARE
	DIR DIRECCION:= DIRECCION(NULL,NULL,NULL);
	P PERSONA:= PERSONA(NULL,NULL,NULL,NULL);
	A ALUMNO;
BEGIN
DIR.CALLE:='Versalles 3';
	DIR.CIUDAD:='Madrid';
	DIR.CODIGO_POSTAL:=28931;
	
	P.CODIGO:=1;
	P.CIUDAD:='Navalcarnero';
	P.DIREC:=DIR;
	P.FECHA_NAT:=SYSDATE;
	A:=NEW ALUMNO(P,1,5,10);
	INSERT INTO ALUMNOS VALUES A;
END;
/


//Varray
DECLARE
	CURSOR C1 IS SELECT * FROM AGENDA;
	CADENA VARCHAR2(50);
BEGIN
	FOR I IN C1 LOOP
		DBMS_OUTPUT.PUT_LINE(I.NOMBRE||' NUMERO DE TELEFONOS: '||I.TELEF.COUNT);
		CADENA:='*';
		FOR J IN 1..I.TELEF.COUNT LOOP
			CADENA:=CADENA||I.TELEF(J)||'*';
		END LOOP;
		DBMS_OUTPUT.PUT_LINE(CADENA);
		END LOOP;
END;
/

//Añadir datos a ARRAY
DECLARE
	TEL TELEFONO:= TELEFONO(NULL,NULL,NULL);
BEGIN
	SELECT TELEF INTO TEL FROM AGENDA WHERE NOMBRE='LUIS';
	DBMS_OUTPUT.PUT_LINE(TEL.COUNT);
	TEL.EXTEND;
	/*SELECCIONAR LA POSICION A MODIFICAR (INDICE INICIAL ES 1)*/
	TEL(TEL.COUNT):='11111';
	TEL.EXTEND;
	TEL(TEL.COUNT):='2222';
	UPDATE AGENDA A SET A.TELEF=TEL WHERE NOMBRE='LUIS';
	DBMS_OUTPUT.PUT_LINE(TEL.COUNT);
END;
/

//BORRAR DATOS DE ARRAY
DECLARE
	TEL TELEFONO:=TELEFONO(NULL, NULL, NULL);
BEGIN
	SELECT TELEF INTO TEL FROM AGENDA WHERE NOMBRE='LUIS';
	TEL.DELETE;
	UPDATE AGENDA A SET A.TELEF=TEL WHERE NOMBRE='LUIS';
END;
/

//CREAR TABLA GRUPOS CON CAMPO NOMBRE DE GRUPO Y PERSONAS DEL GRUPO
CREATE TABLE GRUPOS(
	NOMBRE VARCHAR2(15),
	INTEGRANTES PERSONAS);

//AÑADIR DATOS A GRUPOS
DECLARE
	DIR DIRECCION:= DIRECCION('AAA','BBB',123);
	P1 PERSONA:= PERSONA(6,'VALENCIA',DIR,SYSDATE);
	P2 PERSONA:= PERSONA(7,'CACA',DIR,SYSDATE);
	P3 PERSONA:= PERSONA(8,'SSS',DIR,SYSDATE);
	P4 PERSONA:= PERSONA(9,'PAPA',DIR,SYSDATE);
	P5 PERSONA:= PERSONA(10,'PEPE',DIR,SYSDATE);
	P6 PERSONA:= PERSONA(11,'PIPI',DIR,SYSDATE);
	
	G1 PERSONAS:=PERSONAS(P1,P2);
	G2 PERSONAS:=PERSONAS(P3);
	G3 PERSONAS:=PERSONAS(P4,P5,P6);
BEGIN
	INSERT INTO GRUPOS VALUES('GRUPO1',G1);
	INSERT INTO GRUPOS VALUES('GRUPO2',G2);
	INSERT INTO GRUPOS VALUES('GRUPO3',G3);

	
END;
/
//INSERTAR DATOS EN TABLA ANIDADA
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(1, 'RAMOS', TABLA_ANIDADA(
													DIRECCION('CALLE 1','MADRID','12313'),
													DIRECCION('CALLE 2','BARCELIONA','111'),
													DIRECCION('CALLE 3','MADRID','6666')
													)
										);
										
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES('2','PEREZ',TABLA_ANIDADA());