CREATE OR TELEFONOS AS VARRAY(2) OF NUMBER(9);

CREATE OR REPLACE NOTAS AS VARRAY(5) OF NUMBER(4,2);
	

CREATE OR REPLACE TYPE ALUMNO AS OBJECT(
	DNI VARCHAR2(10);
	NOMBRE VARCHAR2(50);
	DIR DIRECCION;
	TELF TELEFONOS;
	FECHA_NAC DATE;
	ID_CURSO NUMBER(4);
);

CREATE OR REPLACE TYPE ASIGNATURA AS OBJECT(
	COD_ASIG NUMBER(4),
	NOMBRE VARCHAR2(80),
	TIPO CHAR(1)
);

CREATE OR REPLACE TABLE TASIGNATURAS AS TABLE OF ASIGNATURA;

CREATE OR REPLACE TYPE CURSO AS OBJECT(
	ID_CURSO NUMBER(4),
	DESCRIPCION VARCHAR2(60),
	NIVEL VARCHAR2(30),
	TURNO CHAR(1)
);

HOLII