CREATE OR TELEFONOS AS VARRAY(5) OF NUMBER(9);

CREATE OR REPLACE NOTAS AS VARRAY(5) OF NUMBER(4,2);
	

CREATE OR REPLACE TYPE ALUMNO AS OBJECT(
	DNI VARCHAR2(10);
	NOMBRE VARCHAR2(50);
	DIR DIRECCION;
	TELF TELEFONOS;
	FECHA_NAC DATE;
	ID_CURSO NUMBER(4);
);